{% set name = "HyperTS" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DataCanvasIO/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 792f4011feadb838f03f664278ec8333eb875183f993e69ff6a0578df65a0351

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - sktime >=0.8.1
    - hypernets >=0.2.5.1, <0.2.6
    - prophet ==1.0.1
    - statsmodels >=0.12.1
    - numpy >=1.16.5, <1.22 # remove upper bound when the issue is fixed. 'https://github.com/conda-forge/sktime-feedstock/issues/31
    - pandas >=0.25.3
    - scikit-learn >=0.22.1
    - scipy <1.8.0 # remove this line when the issue is fixed. https://github.com/conda-forge/sktime-feedstock/issues/31
  run_constrained:
    - tensorflow >=2.0

test:
  imports:
    - hyperts
    - hyperts.tests
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/DataCanvasIO/HyperTS
  license: Apache-2.0
  license_file: LICENSE
  summary: A Full-Pipeline AutoML&AutoDL Toolkit about Time Series.
  description: |
    HyperTS is a Python package that provides an end-to-end time series (TS) analysis toolkit. 
    It covers complete and flexible AutoML workflows for TS, including data clearning, preprocessing, feature engineering, model selection, hyperparamter optimization, result evaluation, and visualization.
  doc_url: https://hyperts.readthedocs.io/
  dev_url: https://github.com/DataCanvasIO/HyperTS

extra:
  recipe-maintainers:
    - oaksharks
